language: node_js
node_js:
- stable
notifications:
  slack:
    secure: eh6E6WvUBgOdTc2H/p/sZH38l/jytQFknP+VZB1R2NsO8FQlx4sPxvowQ2WNVemwFPo/BPg19kk0JE9T7/qj6Gi71kTdAsV3FUUPDQqopyC9jo2vGtorRHIUyzk6WOM+1LMHdYkY7nZ2YjCHcGvPbBmAgqQKEidFCbii8t1i90nGarH169CavSKCPZCdfjH5KAoliou5Ioz4vIQiyqVWglFxpuknG9pEBV/Wk0d4ogrBv1kjI03kPqrLjnMZJUbHTPP5iEyBdFfQeaJXmK8Zl51x5bR0z5ii6rjMukTk8QJMQEGM9qMVnio6NlHHCkGO5SMjqJ2FMcoRCc+GUwTyoo7cXmKS5Tw3eyWUJwLT5a34gzcr7gbn9MI68Gr7z2UcGm2ip9Hdx4FyIJTemiJJosJhfd538BY+UoLyGhqWY0IkAdsm5TxIUck8hT70co1dWlL4owsPuiIbjW7jygfQ6kE5R4GgFoD1uE0PZiE0SwlEubz8m96nzq/hHeWKaiB6C7gPhSKPy4fHGoGCB5EwRuevewCH6/3HL7UYy+VuhOZcm0+YJQBA1bYS73HwvnHeiSHHLpMj5+874to4/4IKiOm1AQN/aD8V5+z0kar3HiHf41+gwHrBIQT0fqCrtQubLKmcUL89pNGXU1Yy9BdfcEzDna4If2u2W7j86XTlWOM=
  email: false
